server:
  port: 8081

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**