server:
  port: 8080

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/,classpath:/frontend/build/
  mvc:
    static-path-pattern: /**